# Generated by Django 6.1 on 2026-08-10 16:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When the underlying occurrence happened (not when this row was created).",
                        verbose_name="occurred at",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Free-text label supplied by the ingesting host (e.g. a tag or category).",
                        max_length=200,
                        verbose_name="label",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Origin identifier for the event feed (e.g. an importer name).",
                        max_length=100,
                        verbose_name="source",
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        help_text="Stable identifier from the source, used for idempotent re-import.",
                        max_length=255,
                        verbose_name="source id",
                    ),
                ),
                ("body", models.TextField(blank=True, verbose_name="body")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="metadata"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created at"
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="blog_core.article",
                        verbose_name="article",
                    ),
                ),
            ],
            options={
                "verbose_name": "article event",
                "verbose_name_plural": "article events",
                "ordering": ["occurred_at", "pk"],
                "indexes": [
                    models.Index(
                        fields=["article", "occurred_at"],
                        name="blog_core_e_article_a7e8a1_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "source_id"),
                        name="blog_core_events_articleevent_source_uniq",
                    )
                ],
            },
        ),
    ]
